# ????? ????????? ???????
sonar.projectKey=lab2
sonar.organization=StasRimashewskii
sonar.host.url=https://sonarcloud.io

# ????????? ??? ???????
sonar.sources=src
sonar.java.binaries=target/classes

# ?????????, ??? ??????? ???? Java
sonar.language=java